name: 🛬 Release Finish
on:
  workflow_dispatch:
permissions:
  contents: write
run-name: 🛬 release-finish
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Generate CI token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.CI_BOT_APP_ID }}
          private-key: ${{ secrets.CI_BOT_PRIVATE_KEY }}

      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
      - uses: ./.github/actions/release_finish
        with:
          token: ${{ steps.app-token.outputs.token }}
